### ISSUE TITLE
Tag issues check does not flag missing tags in NEXT repetitions

### ISSUE THREAD

**Issue by msoutopico** [capstanlqc/omegat#2]
Missing tags in "NEXT" instances of a repeated segment are not flagged when running Tools > Check issues > Tag issues.

## Preconditions

The project attached contains a repeated segment which appears twice.
Tags are missing in the translation of the second instance.

## Steps to reproduce

Open the project attached.
Run Tag issues check

## Expected result

It flags the missing tags in segment 2.

## Actual result

No issues flagged

## Other info

The missing tag issue in segment 2 is flagged when option Preferences > Editor > *Validate tags when leaving a segment* is active.

## Files
[test-missing-tag-next-rep-omt.omt.zip](https://github.com/capstanlqc/omegat/files/14324252/test-missing-tag-next-rep-omt.omt.zip)

**Comment by t-cordonnier** [comment]
Problem confirmed, I could reproduce it; under investigation

**Comment by msoutopico** [comment]
Hi @t-cordonnier, was there a fix for this issue? is there a feature branch to test it?

**Comment by t-cordonnier** [comment]
Yes: https://github.com/t-cordonnier/omegat/tree/capstan-correct-duplicates-issues

**Comment by msoutopico** [comment]
Thank you @t-cordonnier. The issue seems fixed!
